### ISSUE TITLE
Фильтрация тестов в go

### ISSUE THREAD

**Issue by jayjaytrn** [ozontech/allure-go#5]
Добрый день,
Настраиваем у себя тестопс в связке с go и gitlab, столкнулись с такой проблемой что не работает фильтрация тестов при запуске.
Наш пайплайн:
```
stages:
  - test

variables:
  ALLURE_LAUNCH_NAME: "${CI_PROJECT_NAME} - ${CI_COMMIT_SHORT_SHA}"
  ALLURE_LAUNCH_TAGS: "regular, ${CI_COMMIT_REF_NAME}"
  ALLURE_TESTPLAN_PATH: "./testplan.json"
  ALLURE_RESULTS: "allure-results"

test:
  image: golang:latest
  stage: test
  before_script:
    - wget https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_386 -O /usr/bin/allurectl
    - chmod +x /usr/bin/allurectl

    - allurectl job-run start
    - allurectl job-run plan --output-file ${ALLURE_TESTPLAN_PATH}

  script:
    - mkdir -p allure-results
    - allurectl watch --results ${ALLURE_RESULTS} -- go test -v
  after_script:
    - pkill allurectl
```

При запуске пайплайна есть строки:
```
$ allurectl job-run plan --output-file ${ALLURE_TESTPLAN_PATH}
Save test plan for [7] to file [/builds/test-framework-allure-testops/testplan.json]
```
```
Save test plan for [7] to file [/builds/test-framework-allure-testops/tests/acl]
Running command:  go [test -v]
```
Из этого сделал вывод что интеграция настроена корректно и проблема непосредственно в allurectl job-run plan --output-file ${ALLURE_TESTPLAN_PATH} что подтвердил Артем Ерошенко

Просьба взять на доработку
